### ISSUE TITLE
stop putting the rest of us to shame!

### ISSUE THREAD

**Issue by rowanwins** [adamsteer/f4g-oceania-pdal#2]
Boooo!

Heckle!!

**Comment by keithamoss** [comment]
"Close - Won't Fix?" :D

**Comment by rowanwins** [comment]
Partially resolved - https://github.com/rowanwins/foss4g-ws101

**Comment by keithamoss** [comment]
Hah!

By the way, I'm at a loose end for the morning workshops. Happy to help out if you get a lot of people and need someone to help folks who get stuck during the hands-on portion.

**Comment by keithamoss** [comment]
Neato! Are the debugging tools and Leaflet bit the only hands-on components?

**Comment by adamsteer** [comment]
@rowanwins have you even read the content yet? …even what’s there is full of typos 😄

**Comment by rowanwins** [comment]
Yep pretty much @keithamoss
